"""Add workout_templates table

Revision ID: 71b150997599
Revises: 8d34b7cf7444
Create Date: 2026-05-06 12:09:12.403040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b150997599'
down_revision = '8d34b7cf7444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic  ###
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('exercises', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_templates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_templates_user_id'))

    op.drop_table('workout_templates')
    # ### end Alembic commands ###
